- name: ZAP Full Scan
  on: push
  # You may pin to the exact commit or the version.
  # uses: zaproxy/action-full-scan@d2a07475d467566c9a3e3c700f31f47724aa1060
  uses: zaproxy/action-full-scan@v0.10.0
  with:
    # GitHub Token to create issues in the repository
    token: # optional, default is ${{ github.token }}
    # Target URL
    target: 
    # Relative path of the ZAP configuration file
    rules_file_name: # optional
    # The Docker file to be executed
    docker_name: # default is ghcr.io/zaproxy/zaproxy:stable
    # Additional command line options
    cmd_options: # optional
    # The title for the GitHub issue to be created
    issue_title: # optional, default is ZAP Full Scan Report
    # The action status will be set to fail if ZAP identifies any alerts during the full scan
    fail_action: # optional
    # Whether Github issues should be created or not
    allow_issue_writing: # optional, default is true
    # The name of the artifact that contains the ZAP reports
    artifact_name: # optional, default is zap_scan
          
